services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - bd-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - bd-net

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    networks:
      - bd-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 10s
      retries: 10

  spark:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    networks:
      - bd-net

  flask:
    build: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - cassandra
    networks:
      - bd-net

  processor:
    build: ./processor
    depends_on:
      - kafka
      - spark
      - cassandra
    volumes:
      - ./processor:/app
    networks:
      - bd-net

networks:
  bd-net:
